notifications:
  - provider: Email
    to:
      - zabbix.dov@gmail.com
      - roel@huybrechts.re
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
      PYDOV_BASE_URL: "https://oefen.dov.vlaanderen.be/"
      PYDOV_UPDATE_TESTDATA: "true"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
      PYDOV_UPDATE_TESTDATA: "true"
install:
    # Use the pre-installed Miniconda for the desired arch
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe update -y -q conda
    - cmd: conda.exe config --add channels conda-forge
    - cmd: conda.exe install -y -q python=%CONDA_PY:~0,1%.%CONDA_PY:~1,2%
    - cmd: conda.exe install -y -q numpy pandas owslib
    - cmd: call %CONDA_INSTALL_LOCN%\python.exe -m pip install --ignore-installed --no-cache-dir -r requirements_appveyor.txt

build: false

before_test:
    - cmd: set PYTHONPATH=%PYTHONPATH%;%APPVEYOR_BUILD_FOLDER%
    - ps: if($env:PYDOV_UPDATE_TESTDATA) { & ($env:CONDA_INSTALL_LOCN + "\python.exe") tests\data\update_test_data.py }

test_script:
  - pytest
